{
    'name': 'Match Ticket Booking',
    'version': '1.0',
    'summary': 'Manage users, tickets, bookings, and payments',
    'description': 'A complete module to manage football match tickets based on class diagram.',
    'author': ' IS TEAM ' ,
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/data.xml',
        'views/views.xml',
        'reports/ticket_report.xml',
    ],
    'application': True,
    'installable': True,
    'category': 'Sales',
    'sequence': 1,
    'website': "https://github.com/MohamedFathy610/odoo-match-tickets/blob/main/classdaigram.jpeg",
}